# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters: 
    upload_nc_photos_dir: '%kernel.project_dir%/%env(UPLOAD_NC_PHOTOS_DIR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Injection du dossier upload dans CertificateHandler
    App\Service\CertificateHandler:
        arguments:
            $uploadNcPhotosDir: '%upload_nc_photos_dir%'